"""empty message

Revision ID: 2716941919a2
Revises: c6714e810146
Create Date: 2024-10-04 10:39:32.402523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2716941919a2'
down_revision = 'c6714e810146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('breed', sa.String(), nullable=True))
    op.add_column('pets', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'age')
    op.drop_column('pets', 'breed')
    # ### end Alembic commands ###
